FROM mcr.microsoft.com/dotnet/sdk:{{DOTNET_MAJOR}}.0 AS build
WORKDIR /src
COPY GameServer.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o /app --no-restore
RUN mkdir -p /src/Generated/Migrations

FROM mcr.microsoft.com/dotnet/aspnet:{{DOTNET_MAJOR}}.0
WORKDIR /app
COPY --from=build /app .
COPY --from=build /src/Generated/Migrations ./Migrations
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "GameServer.dll"]
