using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Tjdtjq5.GameServer.SourceGen
{
    [Generator]
    public class ServerLogicGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var classes = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Tjdtjq5.GameServer.ServerLogicAttribute",
                    predicate: (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, _) => GetInfo(ctx))
                .Where(info => info != null);

            context.RegisterSourceOutput(classes.Collect(), Generate);

            // 디버그: Source Generator가 실행되는지 확인용 마커
            context.RegisterPostInitializationOutput(ctx =>
            {
                ctx.AddSource("ServerProxy.Marker.g.cs",
                    SourceText.From(
                        "// Source Generator is running!\n" +
                        "public static partial class ServerProxy\n{\n" +
                        "    public static string __GeneratorVersion => \"1.0.0\";\n" +
                        "}\n",
                        Encoding.UTF8));
            });
        }

        static SvcInfo GetInfo(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol cls) return null;

            var ns = cls.ContainingNamespace;
            var info = new SvcInfo
            {
                Name = cls.Name,
                FullName = ns != null && !ns.IsGlobalNamespace
                    ? $"global::{ns.ToDisplayString()}.{cls.Name}"
                    : $"global::{cls.Name}"
            };

            foreach (var m in cls.GetMembers().OfType<IMethodSymbol>())
            {
                if (m.DeclaredAccessibility != Accessibility.Public || m.IsStatic || m.MethodKind != MethodKind.Ordinary)
                    continue;

                string inner = null;
                if (m.ReturnType is INamedTypeSymbol nr && nr.IsGenericType && nr.TypeArguments.Length == 1)
                    inner = nr.TypeArguments[0].ToDisplayString();

                info.Methods.Add(new MInfo
                {
                    Name = m.Name,
                    Inner = inner,
                    Params = m.Parameters.Select(p => (p.Type.ToDisplayString(), p.Name)).ToList()
                });
            }

            return info.Methods.Count > 0 ? info : null;
        }

        static void Generate(SourceProductionContext ctx, ImmutableArray<SvcInfo> all)
        {
            if (all.IsDefaultOrEmpty) return;

            var w = new CodeWriter();
            w.Line("// <auto-generated by GameServer SourceGen/>");
            w.Line("#pragma warning disable CS0105");
            w.Line("using System;");
            w.Line("using System.Threading.Tasks;");
            w.Line("using Tjdtjq5.GameServer;");
            w.Line("");

            // partial class가 아닌 독립 static class로 생성 (Assembly-CSharp에서 동작)
            w.Line("public static partial class ServerProxy");
            w.Open();

            foreach (var svc in all)
            {
                if (svc == null) continue;
                WriteSvc(w, svc);
            }

            w.Close(); // ServerProxy

            ctx.AddSource("ServerProxy.g.cs",
                SourceText.From(w.ToString(), Encoding.UTF8));
        }

        static void WriteSvc(CodeWriter w, SvcInfo svc)
        {
            w.Line($"public static class {svc.Name}");
            w.Open();

            foreach (var m in svc.Methods)
                WriteMethod(w, svc, m);

            w.Close();
        }

        static void WriteMethod(CodeWriter w, SvcInfo svc, MInfo m)
        {
            bool hasReturn = m.Inner != null;
            string respType = hasReturn ? $"ServerResponse<{m.Inner}>" : "ServerResponse";
            string paramDecl = string.Join(", ", m.Params.Select(p => $"{p.Item1} {p.Item2}"));
            string paramPass = string.Join(", ", m.Params.Select(p => p.Item2));
            string endpoint = $"{svc.Name}/{m.Name}";

            string anonObj = m.Params.Count > 0
                ? $"new {{ {string.Join(", ", m.Params.Select(p => p.Item2))} }}"
                : "null";

            w.Line($"public static async Task<{respType}> {m.Name}({paramDecl})");
            w.Open();

            // 배포됨 → HTTP
            w.Line($"if (Tjdtjq5.GameServer.DeployRegistry.IsDeployed(\"{endpoint}\"))");
            w.Open();
            if (hasReturn)
                w.Line($"return await Tjdtjq5.GameServer.GameServer.Client.PostAsync<{m.Inner}>(\"api/{endpoint}\", {anonObj});");
            else
                w.Line($"return await Tjdtjq5.GameServer.GameServer.Client.PostAsync(\"api/{endpoint}\", {anonObj});");
            w.Close();

            // 미배포 → LocalGameDB
            w.Line("try");
            w.Open();
            w.Line($"var __db = Tjdtjq5.GameServer.GameServer.LocalDB;");
            w.Line($"var __svc = new {svc.FullName}(__db);");
            if (hasReturn)
            {
                w.Line($"var __r = await __svc.{m.Name}({paramPass});");
                w.Line($"return new {respType} {{ success = true, data = __r, statusCode = 200 }};");
            }
            else
            {
                w.Line($"await __svc.{m.Name}({paramPass});");
                w.Line($"return new ServerResponse {{ success = true, statusCode = 200 }};");
            }
            w.Close();
            w.Line("catch (Exception __ex)");
            w.Open();
            w.Line($"return new {respType} {{ success = false, error = __ex.Message, errorType = ErrorType.ServerError, statusCode = 500 }};");
            w.Close();

            w.Close(); // method
        }
    }

    class CodeWriter
    {
        readonly StringBuilder _sb = new StringBuilder();
        int _indent;

        public void Line(string text) => _sb.AppendLine($"{new string(' ', _indent * 4)}{text}");
        public void Open() { Line("{"); _indent++; }
        public void Close() { _indent--; Line("}"); }
        public override string ToString() => _sb.ToString();
    }

    class SvcInfo
    {
        public string Name;
        public string FullName;
        public List<MInfo> Methods = new List<MInfo>();
    }

    class MInfo
    {
        public string Name;
        public string Inner;
        public List<(string, string)> Params;
    }
}
