using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Tjdtjq5.GameServer.SourceGen
{
    [Generator]
    public class TableDataQueryGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // [TableData] 스캔
            var tableClasses = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Tjdtjq5.GameServer.TableDataAttribute",
                    predicate: (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, _) => GetDataInfo(ctx))
                .Where(info => info != null);

            // [SpecData] 스캔
            var specClasses = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Tjdtjq5.GameServer.SpecDataAttribute",
                    predicate: (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, _) => GetDataInfo(ctx))
                .Where(info => info != null);

            // 합치기
            var all = tableClasses.Collect()
                .Combine(specClasses.Collect());

            context.RegisterSourceOutput(all, Generate);
        }

        static DataInfo GetDataInfo(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol cls) return null;

            var info = new DataInfo { Name = cls.Name };

            foreach (var m in cls.GetMembers().OfType<IFieldSymbol>())
            {
                if (m.DeclaredAccessibility != Accessibility.Public) continue;
                if (m.IsStatic || m.IsConst) continue;

                // [ServerOnly] 제외
                bool isServerOnly = m.GetAttributes().Any(a =>
                    a.AttributeClass?.Name == "ServerOnlyAttribute");
                if (isServerOnly) continue;

                info.Fields.Add(new FieldDef
                {
                    Name = m.Name,
                    Type = m.Type.ToDisplayString(),
                    TypeKind = ClassifyType(m.Type.ToDisplayString())
                });
            }

            return info.Fields.Count > 0 ? info : null;
        }

        static FieldTypeKind ClassifyType(string type)
        {
            switch (type)
            {
                case "string": return FieldTypeKind.String;
                case "int":
                case "long":
                case "float":
                case "double": return FieldTypeKind.Numeric;
                case "bool": return FieldTypeKind.Bool;
                case "System.DateTime": return FieldTypeKind.DateTime;
                default: return FieldTypeKind.Other;
            }
        }

        static void Generate(SourceProductionContext ctx,
            (ImmutableArray<DataInfo> Tables, ImmutableArray<DataInfo> Specs) data)
        {
            var allInfos = new List<DataInfo>();
            if (!data.Tables.IsDefaultOrEmpty) allInfos.AddRange(data.Tables.Where(x => x != null));
            if (!data.Specs.IsDefaultOrEmpty) allInfos.AddRange(data.Specs.Where(x => x != null));

            if (allInfos.Count == 0) return;

            // 각 타입별 Query 클래스 생성
            foreach (var info in allInfos)
            {
                var w = new CodeWriter();
                WriteQueryClass(w, info);
                ctx.AddSource($"{info.Name}Query.g.cs",
                    SourceText.From(w.ToString(), Encoding.UTF8));
            }

            // ServerProxy.Query{Type} 메서드 생성
            var pw = new CodeWriter();
            WriteProxyQueryMethods(pw, allInfos);
            ctx.AddSource("ServerProxy.Queries.g.cs",
                SourceText.From(pw.ToString(), Encoding.UTF8));
        }

        static void WriteQueryClass(CodeWriter w, DataInfo info)
        {
            w.Line("// <auto-generated by GameServer SourceGen/>");
            w.Line("using System;");
            w.Line("using System.Collections.Generic;");
            w.Line("using System.Linq;");
            w.Line("");
            w.Line($"public class {info.Name}Query");
            w.Open();

            w.Line($"internal List<Func<global::{info.Name}, bool>> _filters = new List<Func<global::{info.Name}, bool>>();");
            w.Line($"internal Func<IEnumerable<global::{info.Name}>, IEnumerable<global::{info.Name}>> _orderBy;");
            w.Line("internal int? _limit;");
            w.Line("internal int? _offset;");
            w.Line("");

            // 필드별 메서드 생성
            foreach (var f in info.Fields)
            {
                WriteFieldMethods(w, info, f);
                w.Line("");
            }

            // 정렬 메서드
            foreach (var f in info.Fields)
            {
                WriteOrderMethods(w, info, f);
            }
            w.Line("");

            // 페이징
            w.Line($"public {info.Name}Query Limit(int count) {{ _limit = count; return this; }}");
            w.Line($"public {info.Name}Query Offset(int count) {{ _offset = count; return this; }}");
            w.Line("");

            // Execute
            w.Line($"internal List<global::{info.Name}> Execute(List<global::{info.Name}> all)");
            w.Open();
            w.Line($"IEnumerable<global::{info.Name}> result = all;");
            w.Line("foreach (var f in _filters) result = result.Where(f);");
            w.Line("if (_orderBy != null) result = _orderBy(result);");
            w.Line("if (_offset.HasValue) result = result.Skip(_offset.Value);");
            w.Line("if (_limit.HasValue) result = result.Take(_limit.Value);");
            w.Line("return result.ToList();");
            w.Close();

            w.Close(); // class
        }

        static void WriteFieldMethods(CodeWriter w, DataInfo info, FieldDef f)
        {
            string qName = $"{info.Name}Query";
            string fAccess = $"e.{f.Name}";
            string capName = char.ToUpper(f.Name[0]) + f.Name.Substring(1);

            switch (f.TypeKind)
            {
                case FieldTypeKind.String:
                    w.Line($"public {qName} {capName}Equals(string value) {{ _filters.Add(e => {fAccess} == value); return this; }}");
                    w.Line($"public {qName} {capName}Contains(string value) {{ _filters.Add(e => {fAccess} != null && {fAccess}.Contains(value)); return this; }}");
                    break;

                case FieldTypeKind.Numeric:
                    w.Line($"public {qName} {capName}Equals({f.Type} value) {{ _filters.Add(e => {fAccess} == value); return this; }}");
                    w.Line($"public {qName} {capName}GreaterThan({f.Type} value) {{ _filters.Add(e => {fAccess} > value); return this; }}");
                    w.Line($"public {qName} {capName}LessThan({f.Type} value) {{ _filters.Add(e => {fAccess} < value); return this; }}");
                    w.Line($"public {qName} {capName}Between({f.Type} min, {f.Type} max) {{ _filters.Add(e => {fAccess} >= min && {fAccess} <= max); return this; }}");
                    break;

                case FieldTypeKind.Bool:
                    w.Line($"public {qName} {capName}Equals(bool value) {{ _filters.Add(e => {fAccess} == value); return this; }}");
                    break;

                case FieldTypeKind.DateTime:
                    w.Line($"public {qName} {capName}After(System.DateTime value) {{ _filters.Add(e => {fAccess} > value); return this; }}");
                    w.Line($"public {qName} {capName}Before(System.DateTime value) {{ _filters.Add(e => {fAccess} < value); return this; }}");
                    break;
            }
        }

        static void WriteOrderMethods(CodeWriter w, DataInfo info, FieldDef f)
        {
            string qName = $"{info.Name}Query";
            string capName = char.ToUpper(f.Name[0]) + f.Name.Substring(1);

            w.Line($"public {qName} OrderBy{capName}Asc() {{ _orderBy = items => items.OrderBy(e => e.{f.Name}); return this; }}");
            w.Line($"public {qName} OrderBy{capName}Desc() {{ _orderBy = items => items.OrderByDescending(e => e.{f.Name}); return this; }}");
        }

        static void WriteProxyQueryMethods(CodeWriter pw, List<DataInfo> allInfos)
        {
            pw.Line("// <auto-generated by GameServer SourceGen/>");
            pw.Line("using System;");
            pw.Line("using System.Collections.Generic;");
            pw.Line("using System.Threading.Tasks;");
            pw.Line("using Tjdtjq5.GameServer;");
            pw.Line("");
            pw.Line("public static partial class ServerProxy");
            pw.Open();

            foreach (var info in allInfos)
            {
                string respType = $"Tjdtjq5.GameServer.ServerResponse<List<global::{info.Name}>>";

                pw.Line($"public static async Task<{respType}> Query{info.Name}s(Func<{info.Name}Query, {info.Name}Query> queryBuilder)");
                pw.Open();
                pw.Line("try");
                pw.Open();
                pw.Line($"var __db = Tjdtjq5.GameServer.GameServer.LocalDB;");
                pw.Line($"var __all = await __db.GetAll<global::{info.Name}>();");
                pw.Line($"var __q = new {info.Name}Query();");
                pw.Line("__q = queryBuilder(__q);");
                pw.Line("var __result = __q.Execute(__all);");
                pw.Line($"return new {respType} {{ success = true, data = __result, statusCode = 200 }};");
                pw.Close();
                pw.Line("catch (Exception __ex)");
                pw.Open();
                pw.Line($"return new {respType} {{ success = false, error = __ex.Message, errorType = Tjdtjq5.GameServer.ErrorType.ServerError, statusCode = 500 }};");
                pw.Close();
                pw.Close(); // method
                pw.Line("");
            }

            pw.Close(); // ServerProxy
        }
    }

    enum FieldTypeKind { String, Numeric, Bool, DateTime, Other }

    class DataInfo
    {
        public string Name;
        public List<FieldDef> Fields = new List<FieldDef>();
    }

    class FieldDef
    {
        public string Name;
        public string Type;
        public FieldTypeKind TypeKind;
    }
}
