using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Tjdtjq5.SupaRun.SourceGen
{
    /// <summary>
    /// [Config] 클래스에서 PascalCase Def 클래스를 자동 생성하는 Source Generator.
    /// snake_case → PascalCase, [Json(typeof(T))] → 파싱된 타입, [EnumType(typeof(E))] → enum 타입.
    /// </summary>
    [Generator]
    public class DefGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var configClasses = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Tjdtjq5.SupaRun.ConfigAttribute",
                    predicate: (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, _) => GetDefInfo(ctx))
                .Where(info => info != null);

            context.RegisterSourceOutput(configClasses.Collect(), Generate);
        }

        static DefInfo GetDefInfo(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol cls) return null;

            var configName = cls.Name;
            var defName = configName.EndsWith("Config")
                ? configName.Substring(0, configName.Length - 6) + "Def"
                : configName + "Def";

            var info = new DefInfo
            {
                ConfigName = configName,
                DefName = defName
            };

            foreach (var m in cls.GetMembers().OfType<IFieldSymbol>())
            {
                if (m.DeclaredAccessibility != Accessibility.Public) continue;
                if (m.IsStatic || m.IsConst) continue;

                var attrs = m.GetAttributes();

                bool isHidden = attrs.Any(a => a.AttributeClass?.Name == "HiddenAttribute");
                if (isHidden) continue;

                var field = new DefFieldInfo
                {
                    OriginalName = m.Name,
                    PascalName = ToPascalCase(m.Name),
                    OriginalType = m.Type.ToDisplayString(),
                    DefType = m.Type.ToDisplayString(),
                    Kind = DefFieldKind.Normal
                };

                // [Json(typeof(T))] — JSON 자동 파싱
                var jsonAttr = attrs.FirstOrDefault(a => a.AttributeClass?.Name == "JsonAttribute");
                if (jsonAttr != null && jsonAttr.ConstructorArguments.Length > 0)
                {
                    var typeArg = jsonAttr.ConstructorArguments[0];
                    if (typeArg.Kind == TypedConstantKind.Type && typeArg.Value is ITypeSymbol typeSymbol)
                    {
                        field.DefType = typeSymbol.ToDisplayString();
                        field.Kind = DefFieldKind.Json;
                        info.HasJsonFields = true;
                    }
                }

                // [EnumType(typeof(E))] — enum 자동 변환
                var enumAttr = attrs.FirstOrDefault(a => a.AttributeClass?.Name == "EnumTypeAttribute");
                if (enumAttr != null && enumAttr.ConstructorArguments.Length > 0)
                {
                    var typeArg = enumAttr.ConstructorArguments[0];
                    if (typeArg.Kind == TypedConstantKind.Type && typeArg.Value is ITypeSymbol enumSymbol)
                    {
                        field.DefType = enumSymbol.ToDisplayString();
                        field.Kind = DefFieldKind.Enum;
                        info.HasEnumFields = true;
                    }
                }

                info.Fields.Add(field);
            }

            return info.Fields.Count > 0 ? info : null;
        }

        static void Generate(SourceProductionContext ctx, ImmutableArray<DefInfo> defs)
        {
            if (defs.IsDefaultOrEmpty) return;

            foreach (var def in defs)
            {
                if (def == null) continue;
                var w = new CodeWriter();
                WriteDefClass(w, def);
                ctx.AddSource($"{def.DefName}.g.cs",
                    SourceText.From(w.ToString(), Encoding.UTF8));
            }
        }

        static void WriteDefClass(CodeWriter w, DefInfo def)
        {
            w.Line("// <auto-generated by SupaRun DefGenerator/>");
            w.Line($"// {def.ConfigName} → {def.DefName}");
            w.Line("");

            w.Line("namespace Tjdtjq5.SupaRun.Defs");
            w.Open();
            w.Line($"public class {def.DefName}");
            w.Open();

            // 프로퍼티
            foreach (var f in def.Fields)
                w.Line($"public {f.DefType} {f.PascalName} {{ get; set; }}");

            w.Line("");

            // ParseJson 헬퍼 (JSON 필드가 있을 때만)
            if (def.HasJsonFields)
            {
                w.Line("static T ParseJson<T>(string json)");
                w.Open();
                w.Line("if (string.IsNullOrEmpty(json)) return default;");
                w.Line("try { return Newtonsoft.Json.JsonConvert.DeserializeObject<T>(json); }");
                w.Line("catch { return default; }");
                w.Close();
                w.Line("");
            }

            // ParseEnum 헬퍼 (enum 필드가 있을 때만)
            if (def.HasEnumFields)
            {
                w.Line("static T ParseEnum<T>(string value) where T : struct, System.Enum");
                w.Open();
                w.Line("if (string.IsNullOrEmpty(value)) return default;");
                w.Line("if (int.TryParse(value, out var i)) return (T)(object)i;");
                w.Line("return System.Enum.TryParse<T>(value, true, out var e) ? e : default;");
                w.Close();
                w.Line("");
            }

            // FromConfig 정적 메서드
            w.Line($"public static {def.DefName} FromConfig(global::{def.ConfigName} c)");
            w.Open();
            w.Line($"var d = new {def.DefName}();");

            foreach (var f in def.Fields)
            {
                switch (f.Kind)
                {
                    case DefFieldKind.Json:
                        w.Line($"d.{f.PascalName} = ParseJson<{f.DefType}>(c.{f.OriginalName});");
                        break;
                    case DefFieldKind.Enum:
                        w.Line($"d.{f.PascalName} = ParseEnum<{f.DefType}>(c.{f.OriginalName});");
                        break;
                    default:
                        w.Line($"d.{f.PascalName} = c.{f.OriginalName};");
                        break;
                }
            }

            w.Line("return d;");
            w.Close(); // FromConfig

            w.Close(); // class
            w.Close(); // namespace
        }

        /// <summary>snake_case → PascalCase 변환. "max_hp" → "MaxHp", "id" → "Id"</summary>
        static string ToPascalCase(string snakeCase)
        {
            var parts = snakeCase.Split('_');
            var sb = new StringBuilder();
            foreach (var part in parts)
            {
                if (part.Length == 0) continue;
                sb.Append(char.ToUpper(part[0]));
                if (part.Length > 1) sb.Append(part.Substring(1));
            }
            return sb.ToString();
        }
    }

    class DefInfo
    {
        public string ConfigName;
        public string DefName;
        public List<DefFieldInfo> Fields = new List<DefFieldInfo>();
        public bool HasJsonFields;
        public bool HasEnumFields;
    }

    class DefFieldInfo
    {
        public string OriginalName;
        public string PascalName;
        public string OriginalType;
        public string DefType;
        public DefFieldKind Kind;
    }

    enum DefFieldKind { Normal, Json, Enum }
}
