using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Tjdtjq5.SupaRun.SourceGen
{
    [Generator]
    public class ServiceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var classes = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Tjdtjq5.SupaRun.ServiceAttribute",
                    predicate: (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, _) => GetInfo(ctx))
                .Where(info => info != null);

            context.RegisterSourceOutput(classes.Collect(), Generate);
        }

        static SvcInfo GetInfo(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol cls) return null;

            var ns = cls.ContainingNamespace;

            // 생성자 파라미터 전체를 기록
            var ctorParams = new List<CtorParam>();
            var bestCtor = cls.Constructors
                .Where(c => !c.IsImplicitlyDeclared)
                .OrderByDescending(c => c.Parameters.Length)
                .FirstOrDefault();

            if (bestCtor != null)
            {
                foreach (var p in bestCtor.Parameters)
                {
                    var paramNs = p.Type.ContainingNamespace;
                    ctorParams.Add(new CtorParam
                    {
                        TypeName = p.Type.Name,
                        FullTypeName = paramNs != null && !paramNs.IsGlobalNamespace
                            ? $"global::{paramNs.ToDisplayString()}.{p.Type.Name}"
                            : $"global::{p.Type.Name}",
                        IsGameDB = p.Type.Name == "IGameDB",
                    });
                }
            }

            var info = new SvcInfo
            {
                Name = cls.Name,
                FullName = ns != null && !ns.IsGlobalNamespace
                    ? $"global::{ns.ToDisplayString()}.{cls.Name}"
                    : $"global::{cls.Name}",
                CtorParams = ctorParams
            };

            foreach (var m in cls.GetMembers().OfType<IMethodSymbol>())
            {
                if (m.DeclaredAccessibility != Accessibility.Public || m.IsStatic || m.MethodKind != MethodKind.Ordinary)
                    continue;

                // [API] 어트리뷰트가 붙은 메서드만
                if (!m.GetAttributes().Any(a => a.AttributeClass?.Name == "APIAttribute"))
                    continue;

                string inner = null;
                bool isAsync = false;
                var retName = m.ReturnType.ToDisplayString();

                if (retName == "System.Threading.Tasks.Task" || retName == "System.Threading.Tasks.Task")
                {
                    isAsync = true; // Task (void 반환)
                }
                else if (m.ReturnType is INamedTypeSymbol nr && nr.IsGenericType && nr.TypeArguments.Length == 1)
                {
                    var baseName = nr.ConstructedFrom.ToDisplayString();
                    if (baseName.StartsWith("System.Threading.Tasks.Task"))
                    {
                        isAsync = true;
                        inner = nr.TypeArguments[0].ToDisplayString();
                    }
                    else
                    {
                        // ValueTuple 등 비동기가 아닌 제네릭
                        inner = m.ReturnType.ToDisplayString();
                    }
                }
                else if (retName != "void")
                {
                    // 동기 반환 (long, string 등)
                    inner = retName;
                }

                info.Methods.Add(new MInfo
                {
                    Name = m.Name,
                    Inner = inner,
                    IsAsync = isAsync,
                    Params = m.Parameters.Select(p => (p.Type.ToDisplayString(), p.Name)).ToList()
                });
            }

            return info.Methods.Count > 0 ? info : null;
        }

        static void Generate(SourceProductionContext ctx, ImmutableArray<SvcInfo> all)
        {
            if (all.IsDefaultOrEmpty) return;

            var w = new CodeWriter();
            w.Line("// <auto-generated by SupaRun SourceGen/>");
            w.Line("#pragma warning disable CS0105");
            w.Line("using System;");
            w.Line("using System.Threading.Tasks;");
            w.Line("using Tjdtjq5.SupaRun;");
            w.Line("");

            w.Line("namespace Tjdtjq5.SupaRun");
            w.Open();
            w.Line("public static partial class ServerAPI");
            w.Open();

            // 서비스 맵 (의존성 해결용)
            var svcMap = new Dictionary<string, SvcInfo>();
            foreach (var svc in all)
            {
                if (svc != null)
                    svcMap[svc.Name] = svc;
            }

            foreach (var svc in all)
            {
                if (svc == null) continue;
                WriteSvc(w, svc, svcMap);
            }

            w.Close(); // ServerAPI
            w.Close(); // namespace

            ctx.AddSource("ServerAPI.g.cs",
                SourceText.From(w.ToString(), Encoding.UTF8));
        }

        static void WriteSvc(CodeWriter w, SvcInfo svc, Dictionary<string, SvcInfo> svcMap)
        {
            w.Line($"public static partial class {svc.Name}");
            w.Open();

            foreach (var m in svc.Methods)
                WriteMethod(w, svc, m, svcMap);

            w.Close();
        }

        static void WriteMethod(CodeWriter w, SvcInfo svc, MInfo m, Dictionary<string, SvcInfo> svcMap)
        {
            bool hasReturn = m.Inner != null;
            string respType = hasReturn ? $"ServerResponse<{m.Inner}>" : "ServerResponse";
            string paramDecl = string.Join(", ", m.Params.Select(p => $"{p.Item1} {p.Item2}"));
            string paramPass = string.Join(", ", m.Params.Select(p => p.Item2));
            string endpoint = $"{svc.Name}/{m.Name}";

            string anonObj = m.Params.Count > 0
                ? $"new {{ {string.Join(", ", m.Params.Select(p => p.Item2))} }}"
                : "null";

            w.Line($"public static async Task<{respType}> {m.Name}({paramDecl})");
            w.Open();

            // 에디터 전용: 미배포 시 LocalGameDB 로컬 실행 (개발/테스트용)
            // 빌드에서는 이 블록이 컴파일에서 완전히 제외됨
            w.Line("#if UNITY_EDITOR");
            w.Line($"if (!Tjdtjq5.SupaRun.DeployRegistry.IsDeployed(\"{endpoint}\"))");
            w.Open();
            w.Line("try");
            w.Open();

            // IGameDB 인스턴스 (생성자에 필요하면)
            bool needsDb = svc.CtorParams.Any(p => p.IsGameDB);
            if (needsDb)
                w.Line($"var __db = Tjdtjq5.SupaRun.SupaRun.LocalDB;");

            // 의존 서비스 인스턴스 생성
            var created = new HashSet<string>();
            if (needsDb) created.Add("IGameDB");
            EmitDependencies(w, svc, svcMap, created);

            // 서비스 인스턴스 생성
            var ctorArgs = BuildCtorArgs(svc, svcMap);
            w.Line($"var __svc = new {svc.FullName}({ctorArgs});");

            if (hasReturn)
            {
                var call = m.IsAsync
                    ? $"await __svc.{m.Name}({paramPass})"
                    : $"__svc.{m.Name}({paramPass})";
                w.Line($"var __r = {call};");
                w.Line($"return new {respType} {{ success = true, data = __r, statusCode = 200 }};");
            }
            else
            {
                if (m.IsAsync)
                    w.Line($"await __svc.{m.Name}({paramPass});");
                else
                    w.Line($"__svc.{m.Name}({paramPass});");
                w.Line($"return new ServerResponse {{ success = true, statusCode = 200 }};");
            }
            w.Close(); // try
            w.Line("catch (Exception __ex)");
            w.Open();
            w.Line($"return new {respType} {{ success = false, error = __ex.Message, errorType = ErrorType.ServerError, statusCode = 500 }};");
            w.Close(); // catch
            w.Close(); // if (!IsDeployed)
            w.Line("#endif");

            // 빌드: 항상 서버 호출 (로컬 실행 경로 없음)
            // 에디터: 배포된 엔드포인트는 서버 호출
            w.Line($"await Tjdtjq5.SupaRun.SupaRun.WaitForAuth();");
            if (hasReturn)
                w.Line($"return await Tjdtjq5.SupaRun.SupaRun.Client.PostAsync<{m.Inner}>(\"api/{endpoint}\", {anonObj});");
            else
                w.Line($"return await Tjdtjq5.SupaRun.SupaRun.Client.PostAsync(\"api/{endpoint}\", {anonObj});");

            w.Close(); // method
        }

        /// <summary>의존 서비스를 재귀적으로 인스턴스화하는 코드를 생성.</summary>
        static void EmitDependencies(CodeWriter w, SvcInfo svc, Dictionary<string, SvcInfo> svcMap, HashSet<string> created)
        {
            foreach (var param in svc.CtorParams)
            {
                if (param.IsGameDB) continue;
                if (created.Contains(param.TypeName)) continue;

                // 의존 서비스가 svcMap에 있으면 재귀적으로 의존성 해결
                if (svcMap.TryGetValue(param.TypeName, out var depSvc))
                {
                    // 의존 서비스의 의존성 먼저 생성
                    EmitDependencies(w, depSvc, svcMap, created);

                    var depCtorArgs = BuildCtorArgs(depSvc, svcMap);
                    var varName = $"__{param.TypeName.Substring(0, 1).ToLower()}{param.TypeName.Substring(1)}";
                    w.Line($"var {varName} = new {param.FullTypeName}({depCtorArgs});");
                }

                created.Add(param.TypeName);
            }
        }

        /// <summary>생성자 인자 문자열 생성.</summary>
        static string BuildCtorArgs(SvcInfo svc, Dictionary<string, SvcInfo> svcMap)
        {
            if (svc.CtorParams.Count == 0)
                return "";

            var args = new List<string>();
            foreach (var param in svc.CtorParams)
            {
                if (param.IsGameDB)
                {
                    args.Add("__db");
                }
                else
                {
                    var varName = $"__{param.TypeName.Substring(0, 1).ToLower()}{param.TypeName.Substring(1)}";
                    args.Add(varName);
                }
            }
            return string.Join(", ", args);
        }
    }

    class CodeWriter
    {
        readonly StringBuilder _sb = new StringBuilder();
        int _indent;

        public void Line(string text) => _sb.AppendLine($"{new string(' ', _indent * 4)}{text}");
        public void Open() { Line("{"); _indent++; }
        public void Close() { _indent--; Line("}"); }
        public override string ToString() => _sb.ToString();
    }

    class SvcInfo
    {
        public string Name;
        public string FullName;
        public List<CtorParam> CtorParams = new List<CtorParam>();
        public List<MInfo> Methods = new List<MInfo>();
    }

    class CtorParam
    {
        public string TypeName;      // "IGameDB", "CurrencyService" 등
        public string FullTypeName;  // "global::Tjdtjq5.SupaRun.IGameDB" 등
        public bool IsGameDB;
    }

    class MInfo
    {
        public string Name;
        public string Inner;
        public bool IsAsync;
        public List<(string, string)> Params;
    }
}
