using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Tjdtjq5.SupaRun.SourceGen
{
    [Generator]
    public class TableQueryGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var tableClasses = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Tjdtjq5.SupaRun.TableAttribute",
                    predicate: (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, _) => GetDataInfo(ctx))
                .Where(info => info != null);

            var specClasses = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Tjdtjq5.SupaRun.ConfigAttribute",
                    predicate: (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, _) => GetDataInfo(ctx))
                .Where(info => info != null);

            var all = tableClasses.Collect()
                .Combine(specClasses.Collect());

            context.RegisterSourceOutput(all, Generate);
        }

        static DataInfo GetDataInfo(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol cls) return null;

            var info = new DataInfo { Name = cls.Name };

            foreach (var m in cls.GetMembers().OfType<IFieldSymbol>())
            {
                if (m.DeclaredAccessibility != Accessibility.Public) continue;
                if (m.IsStatic || m.IsConst) continue;

                bool isHidden = m.GetAttributes().Any(a =>
                    a.AttributeClass?.Name == "HiddenAttribute");
                if (isHidden) continue;

                info.Fields.Add(new FieldDef
                {
                    Name = m.Name,
                    Type = m.Type.ToDisplayString(),
                    TypeKind = ClassifyType(m.Type.ToDisplayString())
                });
            }

            return info.Fields.Count > 0 ? info : null;
        }

        static FieldTypeKind ClassifyType(string type)
        {
            switch (type)
            {
                case "string": return FieldTypeKind.String;
                case "int":
                case "long":
                case "float":
                case "double": return FieldTypeKind.Numeric;
                case "bool": return FieldTypeKind.Bool;
                case "System.DateTime": return FieldTypeKind.DateTime;
                default: return FieldTypeKind.Other;
            }
        }

        static void Generate(SourceProductionContext ctx,
            (ImmutableArray<DataInfo> Tables, ImmutableArray<DataInfo> Specs) data)
        {
            var allInfos = new List<DataInfo>();
            if (!data.Tables.IsDefaultOrEmpty) allInfos.AddRange(data.Tables.Where(x => x != null));
            if (!data.Specs.IsDefaultOrEmpty) allInfos.AddRange(data.Specs.Where(x => x != null));

            if (allInfos.Count == 0) return;

            foreach (var info in allInfos)
            {
                var w = new CodeWriter();
                WriteQueryClass(w, info);
                ctx.AddSource($"{info.Name}Query.g.cs",
                    SourceText.From(w.ToString(), Encoding.UTF8));
            }

            var pw = new CodeWriter();
            WriteProxyQueryMethods(pw, allInfos);
            ctx.AddSource("ServerAPI.Queries.g.cs",
                SourceText.From(pw.ToString(), Encoding.UTF8));
        }

        // ── Query 클래스 생성 (QueryOptions 기반) ──

        static void WriteQueryClass(CodeWriter w, DataInfo info)
        {
            w.Line("// <auto-generated by SupaRun SourceGen/>");
            w.Line("using Tjdtjq5.SupaRun;");
            w.Line("");
            w.Line($"public class {info.Name}Query");
            w.Open();

            w.Line($"internal QueryOptions _options = new QueryOptions();");
            w.Line("");

            // 필드별 메서드
            foreach (var f in info.Fields)
            {
                WriteFieldMethods(w, info, f);
                w.Line("");
            }

            // 정렬
            foreach (var f in info.Fields)
                WriteOrderMethods(w, info, f);
            w.Line("");

            // 페이징
            w.Line($"public {info.Name}Query Limit(int count) {{ _options.SetLimit(count); return this; }}");
            w.Line($"public {info.Name}Query Offset(int count) {{ _options.SetOffset(count); return this; }}");

            w.Close(); // class
        }

        static void WriteFieldMethods(CodeWriter w, DataInfo info, FieldDef f)
        {
            string qName = $"{info.Name}Query";
            string col = f.Name;
            string capName = char.ToUpper(f.Name[0]) + f.Name.Substring(1);

            switch (f.TypeKind)
            {
                case FieldTypeKind.String:
                    w.Line($"public {qName} {capName}Equals(string value) {{ _options.Eq(\"{col}\", value); return this; }}");
                    w.Line($"public {qName} {capName}Contains(string value) {{ _options.Like(\"{col}\", value); return this; }}");
                    break;

                case FieldTypeKind.Numeric:
                    w.Line($"public {qName} {capName}Equals({f.Type} value) {{ _options.Eq(\"{col}\", value); return this; }}");
                    w.Line($"public {qName} {capName}GreaterThan({f.Type} value) {{ _options.Gt(\"{col}\", value); return this; }}");
                    w.Line($"public {qName} {capName}LessThan({f.Type} value) {{ _options.Lt(\"{col}\", value); return this; }}");
                    w.Line($"public {qName} {capName}Between({f.Type} min, {f.Type} max) {{ _options.Gte(\"{col}\", min); _options.Lte(\"{col}\", max); return this; }}");
                    break;

                case FieldTypeKind.Bool:
                    w.Line($"public {qName} {capName}Equals(bool value) {{ _options.Eq(\"{col}\", value); return this; }}");
                    break;

                case FieldTypeKind.DateTime:
                    w.Line($"public {qName} {capName}After(System.DateTime value) {{ _options.Gt(\"{col}\", value); return this; }}");
                    w.Line($"public {qName} {capName}Before(System.DateTime value) {{ _options.Lt(\"{col}\", value); return this; }}");
                    break;
            }
        }

        static void WriteOrderMethods(CodeWriter w, DataInfo info, FieldDef f)
        {
            string qName = $"{info.Name}Query";
            string capName = char.ToUpper(f.Name[0]) + f.Name.Substring(1);

            w.Line($"public {qName} OrderBy{capName}Asc() {{ _options.OrderByAsc(\"{f.Name}\"); return this; }}");
            w.Line($"public {qName} OrderBy{capName}Desc() {{ _options.OrderByDesc(\"{f.Name}\"); return this; }}");
        }

        // ── ServerAPI.QueryXxx 프록시 (Query 사용) ──

        static void WriteProxyQueryMethods(CodeWriter pw, List<DataInfo> allInfos)
        {
            pw.Line("// <auto-generated by SupaRun SourceGen/>");
            pw.Line("using System;");
            pw.Line("using System.Collections.Generic;");
            pw.Line("using System.Threading.Tasks;");
            pw.Line("using Tjdtjq5.SupaRun;");
            pw.Line("");
            pw.Line("namespace Tjdtjq5.SupaRun");
            pw.Open();
            pw.Line("public static partial class ServerAPI");
            pw.Open();

            foreach (var info in allInfos)
            {
                string respType = $"Tjdtjq5.SupaRun.ServerResponse<List<global::{info.Name}>>";

                pw.Line($"public static async Task<{respType}> Query{info.Name}s(Func<{info.Name}Query, {info.Name}Query> queryBuilder)");
                pw.Open();
                pw.Line("try");
                pw.Open();
                pw.Line($"var __db = Tjdtjq5.SupaRun.SupaRun.LocalDB;");
                pw.Line($"var __q = new {info.Name}Query();");
                pw.Line("__q = queryBuilder(__q);");
                pw.Line($"var __result = await __db.Query<global::{info.Name}>(__q._options);");
                pw.Line($"return new {respType} {{ success = true, data = __result, statusCode = 200 }};");
                pw.Close();
                pw.Line("catch (Exception __ex)");
                pw.Open();
                pw.Line($"return new {respType} {{ success = false, error = __ex.Message, errorType = Tjdtjq5.SupaRun.ErrorType.ServerError, statusCode = 500 }};");
                pw.Close();
                pw.Close(); // method
                pw.Line("");
            }

            pw.Close(); // ServerAPI
            pw.Close(); // namespace
        }
    }

    enum FieldTypeKind { String, Numeric, Bool, DateTime, Other }

    class DataInfo
    {
        public string Name;
        public List<FieldDef> Fields = new List<FieldDef>();
    }

    class FieldDef
    {
        public string Name;
        public string Type;
        public FieldTypeKind TypeKind;
    }
}
